# Generated by Django 5.2.4 on 2025-07-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productattributevalues',
            table='product_attribute_values',
        ),
    ]
