# Generated by Django 5.2.4 on 2025-08-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brands', to='product_app.productbrand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
