# Generated by Django 5.2.4 on 2025-08-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_product_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
