# Generated by Django 5.2.4 on 2025-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_productattributevalues_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalues',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
