# Generated by Django 5.2.4 on 2025-07-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productattributevalues_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
    ]
