# Generated by Django 5.2.4 on 2025-07-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={},
        ),
    ]
