# Generated by Django 5.2.4 on 2025-07-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_remove_productvariant_barcode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributevalues',
            unique_together=set(),
        ),
    ]
