# Generated by Django 5.2.4 on 2025-07-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-id',)},
        ),
    ]
