# Generated by Django 5.2.4 on 2025-07-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_productattributevalues_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ('-id',)},
        ),
    ]
