# Generated by Django 5.2.4 on 2025-07-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_remove_product_attributes_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ('order', '-id')},
        ),
        migrations.AddField(
            model_name='productimages',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='product_app.productvariant'),
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_attributes', to='product_app.productattribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_attribute_values', to='product_app.productattributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='product_app.productvariant')),
            ],
            options={
                'db_table': 'variant_attribute',
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
