# Generated by Django 5.2.4 on 2025-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_attribute_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
