# Generated by Django 5.2.4 on 2025-07-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_productimages_options_productimages_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
