# Generated by Django 5.2.4 on 2025-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_attribute_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
