# Generated by Django 5.2.4 on 2025-07-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_mainsite_images'),
        ('product_app', '0008_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='brand_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brand_images', to='core_app.image'),
        ),
    ]
