# Generated by Django 5.2.4 on 2025-07-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='variant',
        ),
    ]
