# Generated by Django 5.2.4 on 2025-07-19 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_remove_productimages_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
