# Generated by Django 5.2.4 on 2025-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_number',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
