# Generated by Django 5.2.4 on 2025-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_variantattribute_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='social_links',
            field=models.JSONField(blank=True, help_text='you can defined social link by json', null=True),
        ),
    ]
