# Generated by Django 5.2.4 on 2025-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_alter_productvariant_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='alt_text_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='order',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
