# Generated by Django 5.2.4 on 2025-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_alter_product_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_slug',
            field=models.TextField(blank=True),
        ),
    ]
