# Generated by Django 5.2.4 on 2025-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_alter_productimages_alt_text_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id_ba_salam',
            field=models.BigIntegerField(blank=True, help_text='BA Salam ID', null=True),
        ),
    ]
