# Generated by Django 5.2.4 on 2025-08-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
    ]
