# Generated by Django 5.2.4 on 2025-07-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_remove_productvariant_sku_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='social_links',
        ),
    ]
