# Generated by Django 5.2.4 on 2025-07-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_remove_product_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='alt_text_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
