# Generated by Django 5.2.4 on 2025-08-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_alter_productvariant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('-id',)},
        ),
    ]
