# Generated by Django 5.2.4 on 2025-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_alter_productvariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_saled',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
