# Generated by Django 5.2.4 on 2025-07-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_productimages_alt_text_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
