# Generated by Django 5.2.4 on 2025-07-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_product_base_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='ProductAttributeValue',
            new_name='AttributeValue',
        ),
        migrations.RenameModel(
            old_name='VariantAttribute',
            new_name='ProductAttributeValues',
        ),
    ]
