# Generated by Django 5.2.4 on 2025-08-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_product_total_saled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_saled',
            new_name='total_sale',
        ),
    ]
