# Generated by Django 5.2.4 on 2025-08-15 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_rename_total_saled_product_total_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='product_app.attribute'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_favorite_product', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_favorite_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brands', to='product_app.productbrand'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='attribute',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='variant_attributes', to='product_app.attribute'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_product_comments', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_product_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='product_product_image', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='product_app.product'),
        ),
    ]
