# Generated by Django 5.2.4 on 2025-08-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
    ]
