# Generated by Django 5.2.7 on 2025-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0020_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
