# Generated by Django 5.2.7 on 2025-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_productvariant_old_price_productvariant_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
