# Generated by Django 5.2.7 on 2025-10-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0022_productvariant_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock_number',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
