# Generated by Django 5.2.7 on 2025-10-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_alter_productvariant_stock_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='in_person_purchase',
            field=models.BooleanField(default=False, verbose_name='خرید به صورت حضوری'),
        ),
    ]
