# Generated by Django 5.2.7 on 2025-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0024_productvariant_in_person_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='in_person_purchase',
        ),
        migrations.AddField(
            model_name='product',
            name='in_person_purchase',
            field=models.BooleanField(default=False, verbose_name='خرید به صورت حضوری'),
        ),
    ]
