# Generated by Django 5.2.7 on 2025-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0025_remove_productvariant_in_person_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',)},
        ),
    ]
