# Generated by Django 5.2.7 on 2026-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0026_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(max_length=255),
        ),
    ]
