# Generated by Django 5.2.7 on 2025-12-30 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0027_remove_product_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='old_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='in_person_purchase',
            field=models.BooleanField(default=False, verbose_name='خرید به صورت حضوری'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_id_ba_salam',
            field=models.BigIntegerField(blank=True, help_text='BA Salam ID', null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_product_image', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='short_desc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
