# Generated by Django 5.2.7 on 2026-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0027_alter_attribute_attribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute_value',
            field=models.CharField(max_length=255),
        ),
    ]
