# Generated by Django 5.2.7 on 2025-12-30 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0028_remove_product_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_person_purchase',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id_ba_salam',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_sale',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='product_app.attribute'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brands', to='product_app.productbrand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='brand_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_product_comments', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_product_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_attributes', to='product_app.attribute')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_attributes', to='product_app.productvariant')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_values', to='product_app.attributevalue')),
            ],
            options={
                'db_table': 'product_variant_attribute_values',
            },
        ),
        migrations.DeleteModel(
            name='ProductAttributeValues',
        ),
    ]
