# Generated by Django 5.2.7 on 2025-12-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0029_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantattributevalues',
            options={'ordering': ('id',)},
        ),
    ]
