# Generated by Django 5.2.15 on 2026-06-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0028_alter_attributevalue_attribute_value'),
        ('product_app', '0030_alter_productvariantattributevalues_options'),
    ]

    operations = [
    ]
