# Generated by Django 6.0.6 on 2026-06-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0031_merge_20260611_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'ordering': ('id',)},
        ),
    ]
