# Generated by Django 6.0.6 on 2026-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0032_alter_favoriteproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
