# Generated by Django 6.0.6 on 2026-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0033_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sale',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
