# Generated by Django 6.0.6 on 2026-06-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0034_product_total_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattributevalues',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
