# Generated by Django 6.0.6 on 2026-06-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0035_alter_productvariantattributevalues_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantattributevalues',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='productvariantattributevalues',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='product_attributes', to='product_app.product'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productvariantattributevalues',
            table='product_attribute_values',
        ),
    ]
