# Generated by Django 6.0.6 on 2026-06-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0036_remove_productvariantattributevalues_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
