# Generated by Django 5.2.4 on 2025-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=7),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=7),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=7),
        ),
    ]
