# Generated by Django 5.2.4 on 2025-07-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0001_initial'),
        ('product_app', '0006_alter_productimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_discounts', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant_discounts', to='product_app.productvariant'),
        ),
    ]
