# Generated by Django 5.2.4 on 2025-07-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0002_alter_coupon_coupon_type_and_more'),
        ('product_app', '0016_productimages_alt_text_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='product',
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discounts', to='product_app.productvariant'),
        ),
    ]
