# Generated by Django 5.2.4 on 2025-07-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0002_productdiscount_product_and_more'),
        ('product_app', '0006_alter_productimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant_discounts', to='product_app.productvariant'),
        ),
    ]
