# Generated by Django 5.2.4 on 2025-07-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_remove_productdiscount_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'ordering': ('-id',)},
        ),
    ]
