# Generated by Django 5.2.4 on 2025-08-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_alter_coupon_deleted_at_alter_coupon_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='product',
        ),
    ]
