# Generated by Django 5.2.4 on 2025-07-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_alter_productdiscount_product_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-id',)},
        ),
    ]
