# Generated by Django 5.2.4 on 2025-07-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0004_alter_productdiscount_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='number_of_days',
        ),
    ]
