# Generated by Django 5.2.4 on 2025-08-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0004_remove_productdiscount_product'),
        ('product_app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant_discounts', to='product_app.productvariant'),
        ),
    ]
