# Generated by Django 5.2.4 on 2025-07-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0005_remove_coupon_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_use',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='number_of_uses',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
