# Generated by Django 5.2.4 on 2025-08-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0006_alter_productdiscount_product_variant'),
        ('product_app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_discounts', to='product_app.productvariant'),
        ),
    ]
