# Generated by Django 5.2.4 on 2025-08-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0007_alter_productdiscount_product_variant'),
        ('product_app', '0019_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product_variant',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_discounts', to='product_app.productvariant'),
        ),
    ]
