# Generated by Django 5.2.7 on 2026-02-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0008_alter_productdiscount_product_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'ordering': ('id',)},
        ),
    ]
