# Generated by Django 5.2.4 on 2025-07-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',)},
        ),
    ]
