# Generated by Django 5.2.4 on 2025-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_alter_order_deleted_at_alter_order_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='verifypaymentgateway',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='verifypaymentgateway',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
