# Generated by Django 5.2.4 on 2025-07-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_company',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام روش ارسال')),
                ('type', models.CharField(choices=[('standard', 'پست معمولی'), ('express', 'پست پیشتاز'), ('free', 'ارسال رایگان')], default='standard', max_length=20, verbose_name='نوع ارسال')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ارسال')),
                ('estimated_days', models.PositiveIntegerField(verbose_name='تعداد روزهای تخمینی تحویل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='order_app.shippingcompany', verbose_name='شرکت ارسال\u200cکننده')),
            ],
            options={
                'db_table': 'shipping_method',
                'ordering': ('-id',),
            },
        ),
    ]
