# Generated by Django 5.2.7 on 2025-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_paymentgateway_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, verbose_name='نام سفارش دهنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, verbose_name='نام خوانوادگی سفارش دهنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='شماره تماس سفارش دهنده'),
        ),
    ]
