# Generated by Django 5.2.7 on 2025-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_order_first_name_order_last_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='descprtion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
