# Generated by Django 5.2.4 on 2025-07-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_shippingcompany_shippingmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='type',
            new_name='shipping_type',
        ),
    ]
