# Generated by Django 5.2.4 on 2025-07-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_rename_type_shippingmethod_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_shipping_methods', to='order_app.shippingmethod'),
        ),
    ]
