# Generated by Django 5.2.7 on 2025-10-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_order_descprtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='descprtion',
            new_name='description',
        ),
    ]
