# Generated by Django 5.2.7 on 2025-10-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_rename_descprtion_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
