# Generated by Django 5.2.7 on 2025-10-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_order_items_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
