# Generated by Django 5.2.4 on 2025-07-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_orderitem_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('payment_gateway', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_gateways', to='order_app.order')),
            ],
            options={
                'db_table': 'payment_gateway',
            },
        ),
        migrations.CreateModel(
            name='VerifyPaymentGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('result', models.JSONField()),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_payment_gateways', to='order_app.paymentgateway')),
            ],
            options={
                'db_table': 'result_payment_gateway',
            },
        ),
    ]
