# Generated by Django 5.2.7 on 2025-10-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_order_is_reserved_order_reserved_until'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
