# Generated by Django 5.2.7 on 2025-11-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_city_is_active'),
        ('order_app', '0011_alter_order_status'),
        ('product_app', '0025_remove_productvariant_in_person_purchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_address', to='account_app.useraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='account_app.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_shipping_methods', to='order_app.shippingmethod'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='order_app.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant_order_items', to='product_app.productvariant'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_gateways', to='order_app.order'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gateways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verifypaymentgateway',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_payment_gateways', to='order_app.paymentgateway'),
        ),
    ]
