# Generated by Django 5.2.7 on 2025-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_alter_order_address_alter_order_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',)},
        ),
    ]
