# Generated by Django 5.2.7 on 2025-12-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_alter_order_address_alter_order_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_shipping_methods', to='order_app.shippingmethod'),
        ),
    ]
