# Generated by Django 5.2.7 on 2025-12-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_alter_privatenotification_options_and_more'),
        ('order_app', '0015_alter_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_address', to='account_app.useraddress'),
        ),
    ]
