# Generated by Django 5.2.4 on 2025-07-16 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('image', models.ImageField(help_text='Upload the original image file.', upload_to='images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail (can be generated on save).', null=True, upload_to='images/thumbnails/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, help_text='Short descriptive title.', max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility and SEO.', max_length=255, null=True)),
                ('caption', models.TextField(blank=True, help_text='Optional longer caption or description.')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this image (if any).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
