# Generated by Django 5.2.4 on 2025-07-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('image', models.ImageField(help_text='Upload the original image file.', upload_to='images/%Y/%m/%d/')),
                ('image_id_ba_salam', models.BigIntegerField(blank=True, editable=False, help_text='ID of the image in external storage', null=True)),
            ],
            options={
                'db_table': 'core_app_image',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PublicNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'public_notification',
            },
        ),
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('slug_text', models.TextField()),
                ('last_modified', models.CharField(blank=True)),
                ('changefreq', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, default=0.5, help_text='A value between 0.00 and 1.00', max_digits=3)),
            ],
            options={
                'db_table': 'site_map',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('file', models.FileField(upload_to='upload_file/%Y/%m/%d/')),
                ('file_id_ba_salam', models.BigIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'upload_file',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carousel_images', to='core_app.image')),
            ],
            options={
                'db_table': 'carousel',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MainSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('header_title', models.CharField(max_length=50)),
                ('text_color', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(blank=True, related_name='main_site_images', to='core_app.image')),
            ],
            options={
                'db_table': 'main_site',
                'ordering': ('-id',),
            },
        ),
    ]
