# Generated by Django 5.2.4 on 2025-07-24 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('header_title', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('text_color', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(related_name='main_site_images', to='core_app.image')),
            ],
            options={
                'db_table': 'main_site',
                'ordering': ('-id',),
            },
        ),
    ]
