# Generated by Django 5.2.4 on 2025-07-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_mainsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsite',
            name='header_title',
            field=models.CharField(max_length=50),
        ),
    ]
