# Generated by Django 5.2.4 on 2025-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_carousel_deleted_at_alter_carousel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='publicnotification',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='publicnotification',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sitemapentry',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sitemapentry',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
