# Generated by Django 5.2.4 on 2025-07-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_publicnotification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='core_app_image',
        ),
    ]
