# Generated by Django 5.2.4 on 2025-07-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_image_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
