# Generated by Django 5.2.4 on 2025-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_carousel_deleted_at_alter_carousel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='wp_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
