# Generated by Django 5.2.4 on 2025-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_image_wp_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Upload the original image file.', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
