# Generated by Django 5.2.4 on 2025-07-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_remove_image_caption_remove_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
