# Generated by Django 5.2.4 on 2025-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsite',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='main_site_images', to='core_app.image'),
        ),
    ]
