# Generated by Django 5.2.4 on 2025-07-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
    ]
