# Generated by Django 5.2.7 on 2025-10-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsite',
            name='header_title',
            field=models.CharField(max_length=255),
        ),
    ]
