# Generated by Django 5.2.7 on 2025-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_mainsite_header_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='mainsite',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ('id',)},
        ),
    ]
