# Generated by Django 5.2.4 on 2025-07-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_image_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt_text',
        ),
    ]
