# Generated by Django 5.2.4 on 2025-07-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_sitemapentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id_ba_salam',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
