# Generated by Django 5.2.4 on 2025-07-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='notif_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
