# Generated by Django 5.2.4 on 2025-07-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title', models.CharField(help_text='مثلاً خانه، محل کار، ...', max_length=100)),
                ('address_line', models.CharField(help_text='نشانی کامل (خیابان، پلاک، ...)', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='عرض جغرافیایی', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='طول جغرافیایی', max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='آیا آدرس پیش\u200cفرض کاربر است؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_address',
            },
        ),
    ]
