# Generated by Django 5.2.4 on 2025-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_privatenotification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
