# Generated by Django 5.2.4 on 2025-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_privatenotification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='notifi_redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
