# Generated by Django 5.2.4 on 2025-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_remove_profile_display_name_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatenotification',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='privatenotification',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticketroom',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticketroom',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
    ]
