# Generated by Django 5.2.4 on 2025-07-29 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_privatenotification_notifi_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title_room', models.CharField(help_text='عنوان چت روم تیکت', max_length=100)),
                ('subject_room', models.CharField(help_text='موضوع تیکت', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_close', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticker_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticker_room',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('ticket_body', models.TextField(verbose_name='متن تیکت')),
                ('ticket_file', models.FileField(blank=True, null=True, upload_to='ticket/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('sender', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_sender', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='account_app.ticketroom')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ('id',),
            },
        ),
    ]
