# Generated by Django 5.2.4 on 2025-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_privatenotification_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='tel_prefix',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
