# Generated by Django 5.2.4 on 2025-09-18 14:40

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_rename_state_name_state_name_state_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[core.utils.validators.PhoneNumberValidator], verbose_name='mobile phone'),
        ),
    ]
