# Generated by Django 5.2.4 on 2025-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatenotification',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
