# Generated by Django 5.2.4 on 2025-09-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_user_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
