# Generated by Django 5.2.7 on 2025-11-22 08:24

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_city_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatenotification',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='ticketroom',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True, validators=[core.utils.validators.PhoneNumberValidator], verbose_name='mobile phone'),
        ),
    ]
