# Generated by Django 5.2.7 on 2025-12-29 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_city_created_at_city_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='tel_prefix',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='tel_prefix',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
