# Generated by Django 5.2.7 on 2025-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_city_tel_prefix_state_created_at_state_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='tel_prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
