# Generated by Django 5.2.7 on 2025-12-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0013_alter_city_tel_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='is_deleted',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
