# Generated by Django 5.2.10 on 2026-01-24 15:55

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_city_deleted_at_city_is_deleted_state_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=22, unique=True, validators=[core.utils.validators.PhoneNumberValidator], verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]

