# Generated by Django 5.2.15 on 2026-06-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_alter_city_is_active_and_more'),
        ('account_app', '0015_remove_useraddress_is_default_alter_user_email_and_more'),
    ]

    operations = [
    ]
