# Generated by Django 5.2.7 on 2026-01-23 08:48

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_alter_city_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=22, unique=True, validators=[core.utils.validators.PhoneNumberValidator], verbose_name='mobile phone'),
        ),
    ]
