# Generated by Django 5.2.7 on 2026-01-23 09:14

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_alter_user_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=22, unique=True, validators=[core.utils.validators.PhoneNumberValidator], verbose_name='mobile phone'),
        ),
    ]
