# Generated by Django 5.2.7 on 2026-01-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0018_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
    ]
