# Generated by Django 6.0.6 on 2026-06-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_merge_20260611_1704'),
        ('account_app', '0019_remove_useraddress_is_default'),
    ]

    operations = [
    ]
