# Generated by Django 5.2.4 on 2025-07-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryblog',
            name='category_slug',
            field=models.CharField(max_length=500),
        ),
    ]
