# Generated by Django 5.2.4 on 2025-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tagblog',
            name='deleted_at',
            field=models.DateTimeField(db_default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tagblog',
            name='is_deleted',
            field=models.BooleanField(db_default=None, editable=False, null=True),
        ),
    ]
