# Generated by Django 5.2.4 on 2025-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryblog',
            name='category_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tagblog',
            name='tag_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
