# Generated by Django 5.2.4 on 2025-07-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_categoryblog_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryblog',
            table='blog_category',
        ),
    ]
