# Generated by Django 5.2.4 on 2025-07-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_categoryblog_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='post_introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
