# Generated by Django 5.2.7 on 2025-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_postblog_deleted_at_alter_postblog_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tagblog',
            options={'ordering': ('id',)},
        ),
    ]
