# Generated by Django 5.2.7 on 2026-01-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_postblog_options_alter_tagblog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='is_introduction_article',
            field=models.BooleanField(default=False),
        ),
    ]
