# Generated by Django 5.2.7 on 2026-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0019_remove_useraddress_is_default'),
        ('blog_app', '0006_alter_postblog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='post_authors', to='account_app.profile'),
        ),
    ]
