INSERT INTO category(id, category_name, category_slug) VALUES (1850, 'EKO', 'eko');
INSERT INTO category(id, category_name, category_slug) VALUES (2395, 'KADEX', 'kadex');
INSERT INTO category(id, category_name, category_slug) VALUES (2425, 'special-offers', 'special-offers');
INSERT INTO category(id, category_name, category_slug) VALUES (71, 'ابزار اندازه گیری', 'measuringtool');
INSERT INTO category(id, category_name, category_slug) VALUES (66, 'ابزار برش', 'cuttingtool');
INSERT INTO category(id, category_name, category_slug) VALUES (63, 'ابزار برقی', 'electrictools');
INSERT INTO category(id, category_name, category_slug) VALUES (60, 'ابزار دستی', 'handtools');
INSERT INTO category(id, category_name, category_slug) VALUES (64, 'ابزار شارژی', 'rechargeabletools');
INSERT INTO category(id, category_name, category_slug) VALUES (61, 'ابزار لوله کشی', 'plumbingtools');
INSERT INTO category(id, category_name, category_slug) VALUES (91, 'ابزار و تجهیزات ایمنی', '%d8%a7%d8%a8%d8%b2%d8%a7%d8%b1-%d9%88-%d8%aa%d8%ac%d9%87%db%8c%d8%b2%d8%a7%d8%aa-%d8%a7%db%8c%d9%85%d9%86%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (738, 'ابزار و تجهیزات خودرو', '%d8%a7%d8%a8%d8%b2%d8%a7%d8%b1-%d9%88-%d8%aa%d8%ac%d9%87%db%8c%d8%b2%d8%a7%d8%aa-%d8%ae%d9%88%d8%af%d8%b1%d9%88');
INSERT INTO category(id, category_name, category_slug) VALUES (548, 'اسپری و رنگ', '%d8%a7%d8%b3%d9%be%d8%b1%db%8c-%d9%88-%d8%b1%d9%86%da%af');
INSERT INTO category(id, category_name, category_slug) VALUES (62, 'انواع رابط', 'connector');
INSERT INTO category(id, category_name, category_slug) VALUES (713, 'باطری', '%d8%a8%d8%a7%d8%b7%d8%b1%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (1879, 'برند میکا', 'mika');
INSERT INTO category(id, category_name, category_slug) VALUES (526, 'پیچ', '%d9%be%db%8c%da%86');
INSERT INTO category(id, category_name, category_slug) VALUES (537, 'پیچ و مهره، واشر', '%d9%be%db%8c%da%86-%d9%88-%d9%85%d9%87%d8%b1%d9%87%d8%8c-%d9%88%d8%a7%d8%b4%d8%b1');
INSERT INTO category(id, category_name, category_slug) VALUES (93, 'تجهیزات آرایشی و بهداشتی', '%d8%aa%d8%ac%d9%87%db%8c%d8%b2%d8%a7%d8%aa-%d8%a2%d8%b1%d8%a7%db%8c%d8%b4%db%8c-%d9%88-%d8%a8%d9%87%d8%af%d8%a7%d8%b4%d8%aa%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (72, 'تراش و سوراخکاری', 'turninganddrilling');
INSERT INTO category(id, category_name, category_slug) VALUES (119, 'چراغ اضطراری', '%da%86%d8%b1%d8%a7%d8%ba-%d8%a7%d8%b6%d8%b7%d8%b1%d8%a7%d8%b1%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (75, 'چسب', 'glue');
INSERT INTO category(id, category_name, category_slug) VALUES (68, 'خانه و آشپزخانه', 'kitchen');
INSERT INTO category(id, category_name, category_slug) VALUES (74, 'خودرو', 'car');
INSERT INTO category(id, category_name, category_slug) VALUES (15, 'دسته بندی نشده', 'uncategorized');
INSERT INTO category(id, category_name, category_slug) VALUES (1710, 'دینگی DINGQI', '%d8%af%db%8c%d9%86%da%af%db%8c-dingqi');
INSERT INTO category(id, category_name, category_slug) VALUES (581, 'شوینده ،بهداشتی', '%d8%b4%d9%88%db%8c%d9%86%d8%af%d9%87-%d8%8c%d8%a8%d9%87%d8%af%d8%a7%d8%b4%d8%aa%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (607, 'کالای ساختمانی', '%da%a9%d8%a7%d9%84%d8%a7%db%8c-%d8%b3%d8%a7%d8%ae%d8%aa%d9%85%d8%a7%d9%86%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (73, 'کیف ابزار', 'toolbag');
INSERT INTO category(id, category_name, category_slug) VALUES (69, 'لوازم الکتریکی', 'electricalappliances');
INSERT INTO category(id, category_name, category_slug) VALUES (59, 'لوازم بهداشتی', 'toiletries');
INSERT INTO category(id, category_name, category_slug) VALUES (67, 'لوازم و اتصالات لوله کشی', 'plumbingaccessoriesandfittings');
INSERT INTO category(id, category_name, category_slug) VALUES (805, 'لوازم یدکی خانگی', '%d9%84%d9%88%d8%a7%d8%b2%d9%85-%db%8c%d8%af%da%a9%db%8c-%d8%ae%d8%a7%d9%86%da%af%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (1743, 'لیهو LIHU', '%d9%84%db%8c%d9%87%d9%88-lihu');
INSERT INTO category(id, category_name, category_slug) VALUES (65, 'ملزومات جوشکاری', 'weldingsupplies');
INSERT INTO category(id, category_name, category_slug) VALUES (388, 'ملزومات کشاورزی', '%d9%85%d9%84%d8%b2%d9%88%d9%85%d8%a7%d8%aa-%da%a9%d8%b4%d8%a7%d9%88%d8%b1%d8%b2%db%8c');
INSERT INTO category(id, category_name, category_slug) VALUES (70, 'ملزومات گازسوز', 'gasburner');
INSERT INTO category(id, category_name, category_slug) VALUES (1007, 'ملزومات نظافت', '%d9%85%d9%84%d8%b2%d9%88%d9%85%d8%a7%d8%aa-%d9%86%d8%b8%d8%a7%d9%81%d8%aa');
INSERT INTO category(id, category_name, category_slug) VALUES (547, 'یراق آلات', '%db%8c%d8%b1%d8%a7%d9%82-%d8%a2%d9%84%d8%a7%d8%aa');
